### ISSUE TITLE
Unsighty error messages about plug-ins.

### ISSUE THREAD

**Issue by HinTak** [hbons/webkit2-sharp#1]
I adjusted the 12-line webbrowser example to this, and it seems to work okay, except for it giving some unsighty messages:

```
Error loading module '/usr/lib/mozilla/plugins/nppdf.so': /usr/lib/mozilla/plugins/nppdf.so: wrong ELF class: ELFCLASS32
Error scanning plugin /usr/lib/mozilla/plugins/nppdf.so, /usr/libexec/webkit2gtk-4.0/WebKitPluginProcess returned 256 exit status
```
I'd say this probably should be suppressed somehow, since they seem not to matter at all.

**Comment by hbons** [comment]
This doesn't fix the actual issue (I think the plugin doesn't match the architecture?), but you can set Settings.EnablePlugins to ignore plugins.
