### ISSUE TITLE
Unknown license, authors, no readme…

### ISSUE THREAD

**Issue by andrewshadura** [hbons/webkit2-sharp#2]
Could you please populate COPYING, AUTHORS and, possibly, README?
Without those three, this project isn't free software even if it's the intent.

**Comment by spotrh** [comment]
Please, add some sort of clarification as to what the license is on these files.

**Comment by HinTak** [comment]
This is largely auto-generated code from running bindinator ( https://github.com/shana/bindinator ) against webkit2's gobject introspection api , BTW.

**Comment by HinTak** [comment]
See https://github.com/shana/bindinator/issues/26 on the development history, etc of this webkit2-sharp project.

**Comment by hbons** [comment]
Seems like bindinator doesn't have a license either. I assumed it had. Opened an issue there: https://github.com/shana/bindinator/issues/29

**Comment by hbons** [comment]
Fixed.
